### ISSUE TITLE
KTX2 texture support for images on mobile

### ISSUE THREAD

**Issue by ianyimi** [musehq/spacesvr#50]
.ktx2 images do not show up on mobile but they work ok on desktop. I've spent a decent amount of time trying to figure out why this happens. I talked with Don McCurdy about the issue here
https://discourse.threejs.org/t/ktx-texture-loading-with-useloader-r3f/26515/6
I'm not sure what else to link with regards to this problem b/c I have tried a lot of things with no success
This issue can be seen on the starter page on branch ia-ktx

**Comment by alex-shortt** [comment]
fixed
