### ISSUE TITLE
React-dom security problem in Sandbox with React 18 from link on your readme

### ISSUE THREAD

**Issue by DrZedd42** [musehq/spacesvr#98]
The sandbox is broken due to a security issue relating to a change in 17 react-Dom to 18.  How do i get it to work?
![image_2022_08_05T05_56_50_883Z](https://user-images.githubusercontent.com/6352261/183011215-1628ae36-a274-4d59-9223-faa09346a90e.png)
![image_2022_08_05T05_57_35_875Z](https://user-images.githubusercontent.com/6352261/183011217-d33407bf-e39b-426a-a2de-2d5193455c70.png)
![image_2022_08_05T05_57_18_603Z](https://user-images.githubusercontent.com/6352261/183011221-3ed8c306-c9b9-4623-9edb-82d99eccedd0.png)

**Comment by alex-shortt** [comment]
yeahh [getLayoutMap](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap) detect's the users keyboard layout so we can tell them to use either W/A/S/D or Z/Q/S/D, [source here](https://github.com/musehq/spacesvr/blob/e80ca607ef355bfc08eac0d9e76cf14f7063fde8/src/logic/keyboard.ts#L20-L35)

it's annoying but it doesn't cause a crash. you can just click the x at the top right to make it go away.

**Comment by alex-shortt** [comment]
i suppose we could detect if the context is in an iframe and not make that call, defaulting to WASD
